### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by grazzza** [ElrondNetwork/elrond-go#1911]
After being shuffled out, the INFO part of the Termui doesn't update anymore. It keeps hanging in the epoch where the shuffled out action occurred.
I have to do control+C and  cd && ./elrond-utils/termui --address localhost:8080 to see the right epoch and round.

**Comment by LucianMincu** [comment]
👍 This one should be fixed in the [latest release](https://github.com/ElrondNetwork/elrond-go/releases/latest).

**Comment by grazzza** [comment]
Hello Lucian
I still have this error in the termui


Op do 11 jun. 2020 om 18:42 schreef Lucian Mincu <notifications@github.com>:
